project:
  type: website

  # https://quarto.org/docs/publishing/github-pages.html#render-to-docs
  output-dir: docs

website:
  # https://quarto.org/docs/websites/website-tools.html#favicon
  favicon: profile.png

  search: false
  title: "Letters to my past self"
  description: "Societal Progress"
  twitter-card: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/thedch
format:
  html:
    # https://quarto.org/docs/output-formats/html-basics.html
    # https://quarto.org/docs/reference/formats/html.html
    toc: true
    toc-depth: 2
    theme: simplex
    css: styles.css