project:
  type: website
  output-dir: docs

website:
  title: "Letters to my past self"
  description: "Societal Progress"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/thedch
      - icon: twitter
        href: https://twitter.com/nearlydaniel
format:
  html:
    theme: theme.scss
    css: styles.css
