project:
  type: website
  output-dir: rendered

website:
  search: false
  title: "Letters to my past self"
  description: "Societal Progress"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/thedch
format:
  html:
    # https://quarto.org/docs/output-formats/html-basics.html
    # https://quarto.org/docs/reference/formats/html.html
    toc: true
    toc-depth: 2
    theme: simplex
    css: styles.css