project:
  type: website

  # https://quarto.org/docs/publishing/github-pages.html#render-to-docs
  output-dir: docs

website:
  # https://quarto.org/docs/websites/website-tools.html#favicon
  favicon: profile.png

  search: false
  comments: false

  title: "Daniel's Blog"
  description: "Lessons written to my past self."

  # https://quarto.org/docs/websites/website-tools.html#twitter-cards
  twitter-card: true

  navbar:
    pinned: false
    logo: profile.png
    right:
      - icon: github
        href: https://github.com/thedch

format:
  html:
    # https://quarto.org/docs/output-formats/html-basics.html
    # https://quarto.org/docs/reference/formats/html.html
    # toc: true
    # toc-depth: 2
    theme: custom.scss
    css: styles.css

    link-external-icon: true
    link-external-newwindow: true

    # TODO: Experiment with citations and footnotes to make a better reading experience
    citations-hover: false
    footnotes-hover: false

    code-copy: true
    highlight-style: github

    code-block-bg: true
    code-block-border-left: "#31BAE9"

    anchor-sections: true